# Generated by Django 5.2.3 on 2025-08-02 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text="The official name of the seller's store.", max_length=255, unique=True, verbose_name='business name')),
                ('is_active', models.BooleanField(default=False, help_text="Designates whether the seller's products are visible on the site.", verbose_name='active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, max_length=25, verbose_name='contact phone')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='support email')),
                ('business_address', models.TextField(blank=True, verbose_name='business address')),
                ('payout_details_id', models.CharField(blank=True, help_text="Stores the seller's payment account ID from the payment provider (e.g., Stripe Account ID).", max_length=255)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
            },
        ),
    ]
