version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json for TypeScript/JavaScript frontend/backend
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt or pyproject.toml for Python backend
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/" # If you have Terraform modules in root
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/" # For Dockerfile in the root
    schedule:
      interval: "weekly"
