# Generated by Django 5.2.3 on 2025-08-02 07:50

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings

def create_default_seller_and_assign_products(apps, schema_editor):
    """
    1. Finds the superuser (assumed to be the platform owner).
    2. Creates a default Seller profile for this user.
    3. Assigns all existing products to this new default Seller.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Seller = apps.get_model('sellers', 'Seller')
    Product = apps.get_model('store', 'Product')

    # Find the first superuser
    superuser = User.objects.filter(is_superuser=True).order_by('pk').first()

    if not superuser:
        # If no superuser exists, you might want to create one or raise an error.
        # For this script, we'll assume one exists.
        return

    # Create a Seller profile for the superuser
    default_seller, created = Seller.objects.get_or_create(
        user=superuser,
        defaults={'business_name': 'Ltronix-Shop Official'}
    )

    # Assign all products that don't have a seller to the default seller
    Product.objects.filter(seller__isnull=True).update(seller=default_seller)


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller', verbose_name='seller'),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_seller_and_assign_products),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller', verbose_name='seller'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='store_produ_seller__6a8a10_idx'),
        ),
    ]