# ecommerce/store/migrations/0003_order_seller_cart_order_cart.py
# Generated by Django 5.2.3 on 2025-08-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('store', '0002_product_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            # --- IMPORTANT CHANGES HERE ---
            # 1. Removed `default=1` and `preserve_default=False`.
            # 2. Added `null=True` and `blank=True` to allow existing rows to be null initially.
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sellers.seller'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.cart'),
        ),
    ]
