# Generated by Django 5.2.3 on 2025-08-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_seller_cart_order_cart'),
        ('store', '0005_populate_order_sellers'),
    ]

    operations = [
    ]
