web: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A ecommerce worker -l info
beat: celery -A ecommerce beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler