# Generated by Django 5.2.3 on 2025-08-02 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('store', '0003_order_seller_cart_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='The shopping cart associated with this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cart', verbose_name='Associated Cart'),
        ),
    ]
