# Generated by Django 5.2.3 on 2025-06-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('store', '0005_order_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'M-Pesa Transaction', 'verbose_name_plural': 'M-Pesa Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_callback_received',
            field=models.BooleanField(default=False, help_text='True if M-Pesa confirmation callback was received', verbose_name='Callback Received'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='The M-Pesa transaction ID (e.g., KES... )', max_length=100, null=True, verbose_name='M-Pesa Receipt Number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='result_code',
            field=models.CharField(blank=True, help_text='Result code from M-Pesa callback (0 for success)', max_length=10, null=True, verbose_name='Result Code'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='result_desc',
            field=models.TextField(blank=True, help_text='Detailed description from M-Pesa callback', null=True, verbose_name='Result Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='Unique ID from M-Pesa for the checkout process', max_length=255, null=True, unique=True, verbose_name='Checkout Request ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, help_text='Unique ID from M-Pesa for the request', max_length=255, null=True, unique=True, verbose_name='Merchant Request ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Associated Order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20, verbose_name='Transaction Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
