name: Backend CI/CD

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install ruff pytest Django
          pip install -r ecommerce/requirements.txt
        working-directory: ./ecommerce

      - name: Run Ruff Linter
        run: ruff check .
        working-directory: ./ecommerce

      - name: Run Pytest
        run: pytest
        working-directory: ./ecommerce

  build-and-push-docker:
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ecommerce
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest
