name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/my-app

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend/my-app

      - name: Run tests
        run: npm test
        working-directory: ./frontend/my-app
        # Add a placeholder for a test command if one exists, e.g., `npm test`
        # If no tests are configured, this step might fail or do nothing.

      - name: Build Next.js application
        run: npm run build
        working-directory: ./frontend/my-app

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: | 
          npm install -g vercel
          vercel pull --yes --scope ltronix-shop-vercel-scope
          vercel build --prod --scope ltronix-shop-vercel-scope
          vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ltronix-shop-vercel-scope
        working-directory: ./frontend/my-app
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}